app:
  name: CurrentExcahngeApp
  port: 127.0.0.1:3000

database:
  Dsn: root:741109@tcp(127.0.0.1:3306)/Test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenConns: 114

redis:
  addr: localhost:6379
  DB: 0
  Password: ""